spring.application.name=AI_Interview_Platform

spring.data.mongodb.uri=mongodb://localhost:27017/aicopilot
spring.data.mongodb.database=aicopilot
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nitinpachauri937@gmail.com
spring.mail.password=affsayequxlsyrsy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
